version: '3.8'
services:
  redis_server:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dalgo-network 
  backend:
    image: dalgo_backend:latest
    command: backend
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - .env.docker
    volumes:
      - ${CLIENTS_DBT_MOUNT}:/data/clients_dbt
      - ${DEV_SECRETS_MOUNT}:/data/secrets
      - ${LOGS_MOUNT}:/usr/src/backend/ddpui/logs
    networks:
      - dalgo-network
  celery_beat:
    image: dalgo_backend:latest
    command: beat
    depends_on:
      - backend
      - redis_server
    env_file:
      - .env.docker
    volumes:
      - celerybeat_volume:/data
    networks:
      - dalgo-network

  celery_worker:
    image: dalgo_backend:latest
    command: worker
    depends_on:
      - backend
      - redis_server
    env_file:
      - .env.docker
    volumes:
      - ${CLIENTS_DBT_MOUNT}:/data/clients_dbt
      - ${DEV_SECRETS_MOUNT}:/data/secrets
      - ${LOGS_MOUNT}:/usr/src/backend/ddpui/logs
    networks:
      - dalgo-network

volumes:
  redis_data:
  celerybeat_volume:

networks:
  dalgo-network:
    driver: bridge
